version: '3'

services:
  web:
    build: ./server
    ports:
      - "3100:3100"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/domorium
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--", "npm", "start"]
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: domorium
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
